### ISSUE TITLE
Add start experiment check

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#105]
### Summary

Add an implementation to the python function `start_experiment_routine()`. This function is located at `exposed_core.py`.

### Affected area

- [ ] Front-End
- [X] Back-End
- [ ] Other

### Description

When the user press the "ENSAIO" button on main page this function gets called. The backend must complete the following steps (sugestion):

1. Check if granulado (ESP32) is connected.
2. Check if you can start an experiment.
3. Call the JS function `go_to_experiment_page()` and validade its return.

`go_to_experiment_page()` asks the front-end to rout to the experiment page.

Usage example can be found at [https://hefestustec.github.io/bolinho/api/front_end_api/#def-go_to_experiment_page](https://hefestustec.github.io/bolinho/api/front_end_api/#def-go_to_experiment_page).

> Right now this function doesn't check anything, just rout to the experiment page

**Comment by ZRafaF** [comment]
Add a sanity check to the "global parameters"
