### ISSUE TITLE
Add check_can_start_experiment

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#160]
### Summary

A function that the front end calls when the user tries to start an experiment.

### Affected area

- [X] Front-End
- [X] Back-End
- [ ] Other

### Description

Add a function called `check_can_start_experiment` that returns 1 if the experiment can begin and 0 if somethin is not correct.

If something is not correct the backend should display an error message to the user telling what went wrong.

The following flow diagram describes the interaction

```mermaid
  graph TD;
      A[/ENSAIO button/]-->B{"check_can_start_experiment()"};
      B-->|false|C(["display error"]);
      B-->|true|D[/"user creates a new experiment"/];
      D-->E{"post_experiment()"};
      E-->|false|F(["display error"]);
      E-->|true|G["front end calls start_experiment_routine(id)"];
      G-->H(["backend routes to the experiment page"]);
```

This issue is correlated with #105 

### Priority

High

**Comment by GPoleto27** [comment]
The feature was implemented.
