### ISSUE TITLE
Remove virtual keyboard dependencies

### ISSUE THREAD

**Issue by GPoleto27** [HefestusTec/bolinho#174]
### Affected area

- [X] Front-End
- [ ] Back-End
- [ ] Other

### Description

Virtual keyboard will no longer be a part of Bolinho, thus, it's necessary for us to remove it's dependencies.

### Priority

Low

**Comment by zRafaF** [comment]
Remove `virtual keyboard` button on config page

**Comment by GPoleto27** [comment]
Done.
