### ISSUE TITLE
User instructions

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#176]
### Description

Add instructions for the user on the workflow of Bolinho.

* How to configurate the app
* How to calibrate the machine
* How to manually control
* How to create new experiment
* How to inspect an experiment

### Affected area

- [X] Front-End
- [X] Back-End
- [ ] Other

### Documentation version

- [X] Web
- [X] PDF

### Modification type

- [X] Addition
- [ ] Removal
- [ ] Update to existing page

### Priority

High

**Comment by GPoleto27** [comment]
Done.
