### ISSUE TITLE
Sequencial experiment

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#209]
### Description

Trying to start an experiment after another results in the plot not being show

### Affected area

- [X] Front-End
- [X] Back-End

### Expected behavior

Show plot

### Actual behavior

Doesn't show plot

### Reproduction steps

1. start an experiment
2. End experiment
3. Start another experiment
4. bug

### Priority

High

**Comment by GPoleto27** [comment]
Os cara é bom.
