### ISSUE TITLE
Selected port does not persist after running experiment

### ISSUE THREAD

**Issue by GPoleto27** [HefestusTec/bolinho#210]
### Description

After selecting a port on the dropdown menu and connecting to Granulado, start a experiment then end it, when the application returns to the inspection page the dropdown menu selection will be empty, it is expected that the dropdown selection is persisted between states of the application.

### Affected area

- [X] Front-End
- [ ] Back-End

### Expected behavior

The dropdown selection is persisted between states of the application.

### Actual behavior

The dropdown selection is not persisted between states of the application.

### Reproduction steps

- Select a port
- Connect to Granulado
- Start an experiment
- End the experiment
When in the inspecting page again, notice that the dropdown menu for port selection has no selection in it

### Priority

Low

**Comment by zRafaF** [comment]
Quick solution: if is connected do not show the port picker

**Comment by zRafaF** [comment]
Implemented
