### ISSUE TITLE
Serial buffet

### ISSUE THREAD

**Issue by zRafaF** [HefestusTec/bolinho#211]
### Affected area

- [ ] Front-End
- [X] Back-End
- [ ] Other

### Description

Make a buffer that every command is written to it, and only once at process the whole buffer is sent as one, this will decrease de overhead of serial, do this for bolinho and granulado.

This will probably fix the wrong commands error, since there the response will wait for the interrogation 

### Priority

Medium

**Comment by GPoleto27** [comment]
Implemented on Granulado

**Comment by zRafaF** [comment]
Implemented on Bolinho
